discussion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('event/', include('event.urls')),
    path('django_practice/', include('django_practice.urls')),
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

event/urls.py
from django.urls import path

from . import views


app_name = 'event'
urlpatterns = [

	path('', views.index, name='index'),
	# /todoitem/<todoitem_id> route
	path('eventitem<int:eventitem_id>/', views.eventitem, name='eventitem'),
	path('add_event/', views.add_event, name='add_event'),
	path('<int:eventitem_id>/edit', views.update_event, name='update_event'),
	path('<int:eventitem_id>/delete', views.delete_event, name='delete_event'),
]

todolist/urls.py
from django.urls import path

from . import views

'''
	path()
		Syntax:
			path(route, view, name)
'''


app_name = 'todolist'
urlpatterns = [
	# /todoitem route
	path('', views.index, name='index'),
	# /todoitem/<todoitem_id> route
	path('todoitem<int:todoitem_id>/', views.todoitem, name='viewtodoitem'),
	path('register/', views.register, name='register'),
	path('change_password/', views.change_password, name='change_password'),
	path('login/', views.login_view, name='login'),
	path('logout/', views.logout_view, name='logout'),
	path('add_task/', views.add_task, name='add_task'),
	path('<int:todoitem_id>/edit', views.update_task, name='update_task'),
	path('<int:todoitem_id>/delete', views.delete_task, name='delete_task'),
	path('update_user/', views.update_user, name='update_user'),
]

event/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.
class Event(models.Model):
    event_name = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    status = models.CharField(max_length=50, default="pending")
    event_date = models.DateTimeField('event date')
    user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

event/forms.py
from django import forms




class AddEventForm(forms.Form):
	event_name = forms.CharField(label='Event Name', max_length=100)
	description = forms.CharField(label='Description', max_length=200)


class UpdateEventForm(forms.Form):
	event_name = forms.CharField(label='Task Name', max_length=100)
	description = forms.CharField(label='Description', max_length=200)
	status = forms.CharField(label='Status', max_length=50)

event/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.forms.models import model_to_dict
from django.utils import timezone
from django.contrib.auth.hashers import make_password
from django.contrib import messages


# Local imports
from .models import Event
from .forms import  AddEventForm, UpdateEventForm


def index(request):
	eventitem_list = Event.objects.filter(user_id=request.user.id)
	context = {'eventitem_list': eventitem_list}
	return render(request, "event/index.html", context)




def eventitem(request, eventitem_id):
	# retrieves the item object using the id or primary key
	eventitem = get_object_or_404(Event, pk=eventitem_id)


	return render(request, "event/eventitem.html", model_to_dict(eventitem))


def add_event(request):
    context = {}
    
    if request.method == 'POST':
        form = AddEventForm(request.POST)

        if form.is_valid():
            event_name = form.cleaned_data['event_name']
            description = form.cleaned_data['description']

            # Check the database if an event with the same name already exists
            duplicates = Event.objects.filter(event_name=event_name)

            # If the event does not contain any duplicates, create it
            if not duplicates:
                event = Event.objects.create(event_name=event_name, description=description, event_date=timezone.now(), user_id=request.user.id)
                event_id = event.id  # Get the newly created event's ID
                return redirect("event:eventitem", eventitem_id=event_id)  # Pass event_id as an argument
            else:
                context = {
                    "error" : True
                }
        else:
            # Pass the form with errors to the template
            context['form'] = form
    
    else:
        form = AddEventForm()
        context['form'] = form

    return render(request, 'event/add_event.html', context)






def update_event(request, eventitem_id):

	eventitem = Event.objects.filter(pk=eventitem_id)

	context = {
		"user" : request.user,
		"eventitem_id" : eventitem_id,
		"event_name" : eventitem[0].event_name,
		"description" : eventitem[0].description,
		"status" : eventitem[0].status
	}

	if request.method == 'POST':
		form = UpdateEventForm(request.POST)

		if form.is_valid() == False:
			form = UpdateEventForm()
		else: 
			event_name = form.cleaned_data['event_name']
			description = form.cleaned_data['description']
			status = form.cleaned_data['status']

			if eventitem:
				eventitem[0].event_name = event_name
				eventitem[0].description = description
				eventitem[0].status = status

				eventitem[0].save()
				return redirect("todolist:index")
			else:
				context = {
					"error" : True
				}
	return render(request, 'event/update_event.html', context)


def delete_event(request, eventitem_id):
	eventitem = Event.objects.filter(pk=eventitem_id).delete()
	return redirect('todolist:index')

event/templates/event/add_event.html
{% extends 'base.html' %}

{% block title %}Add Event{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-6 offset-3">
        <h1 class="text-center my-3 text-success">Add An Event</h1>
        {% if error == True %}
          <p class="text-danger">Duplicate event found</p>
        {% endif %}
        <form action="{% url 'event:add_event' %}" method="post">
          {% csrf_token %}

          <div class="mb-3">
              <label for="event_name" class="text-danger">Event Name: </label>
              <input class="form-control" id="event_name" type="text" name="event_name" value="{{ event_name }}" maxlength="50" required>
          </div>

          <div class="mb-3">
              <label for="description" class="text-danger">Description: </label>
              <textarea class="form-control" name="description" value="{{ description }}" required></textarea>
          </div>

          <div class="text-center">
              <input class="btn btn-primary" type="submit" value="Add Event">
          </div>

        </form>
      </div>
    </div>
  </div>
{% endblock %}

event/templates/event/eventitem.html
{% extends 'base.html'%}

{% block title %} Event Details {% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-6 offset-3">
        <h1 class="text-center my-3 text-success">{{ event_name }}</h1>
        <h3 class="text-center text-primary">Description</h3>
        <p class="text-center text-success">{{ description }}</p>
        <h3 class="text-center text-primary">Status</h3>
        <p class="text-center text-success">{{ status }}</p>
        
        {% if eventitem.id %}
        <button class="btn btn-primary mx-1 text-decoration-none">
          <a href="{% url 'event:update_event' eventitem.id %}" class="text-light text-decoration-none">Edit Event</a>
        </button>

        <button class="btn btn-danger mx-1 text-decoration-none">
          <a href="{% url 'event:delete_event' eventitem.id %}" class="text-light text-decoration-none">Delete Event</a>
        </button>
        {% endif %}
        
        <button class="btn btn-primary mx-auto d-block text-decoration-none">
          <a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">Back Home</a>
        </button>
      </div>
    </div>
  </div>
{% endblock %}

event/templates/event/update_event.html
{% extends 'base.html' %}

{% block title %}Update Event{% endblock %}

{% block content %}
  {% if user.is_anonymous == False %}
    <div class="container">
      <div class="row">
        <div class="col-6 offset-3">
          <h1 class="text-center my-3 text-success">Update Event</h1>
          {% if error == True %}
            <p class="text-danger">Event Not Found!</p>
          {% endif %}
          <form action="{% url 'event:update_event' eventitem_id %}" method="post">
            {% csrf_token %}

            <div class="mb-3">
                <label for="task_name">Event Name: </label>
                <input class="form-control" id="task_name" type="text" name="task_name" value="{{ event_name }}" maxlength="100" required>
            </div>

            <div class="mb-3">
                <label for="description">Description: </label>
                <textarea class="form-control" name="description" required>{{ description }}</textarea>
            </div>

            <div class="mb-3">
                <label for="status">Status: </label>
                <input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
            </div>

            <div class="text-center">
                <input class="btn btn-success" type="submit" value="Update Task">
            </div>

          </form>
        </div>
      </div>
    </div>
  {% else %}
    <h1 class="text-center my-3">You are not authorized to access this page.</h1>
    <p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
  {% endif %}
{% endblock %}