discussion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('event/', include('event.urls')),
    path('django_practice/', include('django_practice.urls')),
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

event/urls.py
from django.urls import path

from . import views


app_name = 'event'
urlpatterns = [

	path('', views.index, name='index'),
	# /todoitem/<todoitem_id> route
	path('eventitem<int:eventitem_id>/', views.eventitem, name='eventitem'),
	path('add_event/', views.add_event, name='add_event'),
	path('<int:eventitem_id>/edit', views.update_event, name='update_event'),
	path('<int:eventitem_id>/delete', views.delete_event, name='delete_event'),
]

todolist/urls.py
from django.urls import path

from . import views

'''
	path()
		Syntax:
			path(route, view, name)
'''


app_name = 'todolist'
urlpatterns = [
	# /todoitem route
	path('', views.index, name='index'),
	# /todoitem/<todoitem_id> route
	path('todoitem<int:todoitem_id>/', views.todoitem, name='viewtodoitem'),
	path('register/', views.register, name='register'),
	path('change_password/', views.change_password, name='change_password'),
	path('login/', views.login_view, name='login'),
	path('logout/', views.logout_view, name='logout'),
	path('add_task/', views.add_task, name='add_task'),
	path('<int:todoitem_id>/edit', views.update_task, name='update_task'),
	path('<int:todoitem_id>/delete', views.delete_task, name='delete_task'),
	path('update_user/', views.update_user, name='update_user'),
]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.
class ToDoItem(models.Model):
	task_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	date_created = models.DateTimeField('date created')
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

todolist/forms.py
from django import forms
from django.contrib.auth.models import User 


class LoginForm(forms.Form):
	username = forms.CharField(label='Username', max_length=20)
	password = forms.CharField(label='Password', max_length=20)



class AddTaskForm(forms.Form):
	task_name = forms.CharField(label='Task Name', max_length=50)
	description = forms.CharField(label='Description', max_length=200)


class UpdateTaskForm(forms.Form):
	task_name = forms.CharField(label='Task Name', max_length=50)
	description = forms.CharField(label='Description', max_length=20)
	status = forms.CharField(label='Status', max_length=50)


class RegisterForm(forms.Form):
    username = forms.CharField(label='Username', max_length=20)
    first_name = forms.CharField(label='First Name', max_length=30)
    last_name = forms.CharField(label='Last Name', max_length=30)
    email = forms.EmailField(label='Email')
    password = forms.CharField(label='Password', widget=forms.PasswordInput())
    confirm_password = forms.CharField(label='Confirm Password', widget=forms.PasswordInput())




class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404
# from django.http import HttpResponse
# from django.template import loader
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict
from django.utils import timezone
from django.contrib.auth.hashers import make_password
from django.contrib import messages
from django.contrib.auth.decorators import login_required


# Local imports
from .models import ToDoItem
from .forms import LoginForm, AddTaskForm, UpdateTaskForm, RegisterForm, UpdateUserForm


# Create your views here.
def index(request):
	todoitem_list = ToDoItem.objects.filter(user_id=request.user.id)
	context = {'todoitem_list': todoitem_list}
	return render(request, "todolist/index.html", context)


def todoitem(request, todoitem_id):
	# retrieves the item object using the id or primary key
	todoitem = get_object_or_404(ToDoItem, pk=todoitem_id)

	# response = "You are viewing the details of %s"
	return render(request, "todolist/todoitem.html", model_to_dict(todoitem))

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            # Check if a user with the same username already exists
            if User.objects.filter(username=username).exists():
                messages.error(request, 'A user with the same username already exists.')
            else:
                # Hash the password using make_password
                hashed_password = make_password(password)

                user_to_register = User.objects.create_user(
                    username=username,
                    first_name=first_name,
                    last_name=last_name,
                    email=email,
                    password=hashed_password,
                )
                user_to_register.is_staff = False
                user_to_register.is_active = True
                user_to_register.save()
                messages.success(request, 'User successfully registered.')

                return redirect('todolist:index')
    else:
        form = RegisterForm()

    return render(request, "todolist/register.html", {"form": form})





def change_password(request):

	is_user_authenticated = False
	user = authenticate(username = "johndoe", password = "john123")
	print(user)


	# Code here executes if the user is successfully authenticated
	if user is not None:
		authenticated_user = User.objects.get(username = "johndoe")
		authenticated_user.set_password("johndoe1")
		authenticated_user.save()
		is_user_authenticated = True


	context = {
		"is_user_authenticated" : is_user_authenticated
	}

	return render(request, "todolist/change_password.html", context)


def login_view(request):
   
    context = {}


    if request.method == 'POST':

    	form = LoginForm(request.POST)

    	if form.is_valid() == False:
    		# Returns a blank login form
    		form = LoginForm()
    	else:
    		# Retrieves the information from the form
    		username = form.cleaned_data['username']
    		password = form.cleaned_data['password']
    		user = authenticate(username=username, password=password)
    		context = {
    			"username" : username,
    			"password" : password
    		}

    	if user is not None:
    		# Saves the user's ID in the session using Django's session framework
    		login(request, user)
    		return redirect('todolist:index')
    	else:
    		# Provides context with error to conditionally render the error message
    		context = {
    			"error" : True
    		}

    return render(request, 'todolist/login.html', context)	

def logout_view(request):
	# removes the saved data in session upon login
    logout(request)
    return redirect("todolist:index")



def add_task(request):
	context = {}

	if request.method == 'POST':
		form = AddTaskForm(request.POST)

		if form.is_valid() == False:
			form = AddTaskForm()
		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']

			# Checks the database if a task is already exists
			duplicates = ToDoItem.objects.filter(task_name=task_name)

			#if todoitem does not contain any duplicates
			if not duplicates:

				ToDoItem.objects.create(task_name=task_name, description=description, date_created=timezone.now(), user_id=request.user.id)

			else:
				context = {
					"error" : True
				}
	return render(request, 'todolist/add_task.html', context)


def update_task(request, todoitem_id):

	todoitem = ToDoItem.objects.filter(pk=todoitem_id)

	context = {
		"user" : request.user,
		"todoitem_id" : todoitem_id,
		"task_name" : todoitem[0].task_name,
		"description" : todoitem[0].description,
		"status" : todoitem[0].status
	}

	if request.method == 'POST':
		form = UpdateTaskForm(request.POST)

		if form.is_valid() == False:
			form = UpdateTaskForm()
		else: 
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']
			status = form.cleaned_data['status']

			if todoitem:
				todoitem[0].task_name = task_name
				todoitem[0].description = description
				todoitem[0].status = status

				todoitem[0].save()
				return redirect("todolist:index")
			else:
				context = {
					"error" : True
				}
	return render(request, 'todolist/update_task.html', context)



def delete_task(request, todoitem_id):
	todoitem = ToDoItem.objects.filter(pk=todoitem_id).delete()
	return redirect('todolist:index')



def update_user(request):
    if request.method == 'POST':
        form = UpdateUserForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('todolist:index')
    else:
        form = UpdateUserForm(instance=request.user)

    return render(request, 'todolist/update_user.html', {'form': form})

todolist/templates/todolist/add_task.html
{% extends 'base.html' %}

{% block title %}Add Task{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-6 offset-3">
        <h1 class="text-center my-3 text-danger">Add A Task</h1>
        {% if error == True %}
          <p class="text-danger">Duplicate task found</p>
        {% endif %}
        <form action="{% url 'todolist:add_task' %}" method="post">
          {% csrf_token %}

          <div class="mb-3">
              <label for="task_name" class="text-success">Task Name: </label>
              <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
          </div>

          <div class="mb-3">
              <label for="description" class="text-success">Description: </label>
              <textarea class="form-control" name="description" value="{{ description }}" required></textarea>
          </div>

          <div class="text-center">
              <input class="btn btn-primary" type="submit" value="Add Task">
          </div>

        </form>
      </div>
    </div>
  </div>
{% endblock %}

todolist/templates/todolist/change_password.html
{% if is_user_authenticated == False %}
	<h1>Invalid User Credentials</h1>
	<p>check if the username and password is correct</p>

{% else %}
	<h1>User Password Successfully Updated!</h1>
	<p>The password has been successfully updated</p>
{% endif %}

todolist/templates/todolist/index.html
{% extends 'base.html'%}

{% block title %} Home {% endblock %}


{% block content %} 
    {% if todoitem_list and not user.is_anonymous %}
        <h1 class="text-center my-5 text-warning"> Welcome {{user.first_name}} {{user.last_name}}!</h1>
        <div class="container">
            <div class="row">
                <h3 class="text-center mb-3 text-success">My Tasks</h3>
                <ul class="list-group mb-5 col-lg-2 offset-lg-5 text-center">
                    {% for todoitem in todoitem_list %}
                        <a href="{% url 'todolist:viewtodoitem' todoitem.id %}" class="text-decoration-none">
                            <li class="list-group-item">{{ todoitem.task_name }}</li>
                        </a>
                    {% endfor %}
                </ul>
            </div>

            <div class="row">
                <h3 class="text-center mt-3 mb-3 text-primary">My Events</h3>
                <ul class="list-group col-lg-2 offset-lg-5 text-center">
                    {% for eventitem in eventitem_list %}
                        <a href="{% url 'event:eventitem' eventitem.id %}" class="text-decoration-none">
                            <li class="list-group-item">{{ eventitem.event_name }}</li>
                        </a>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% elif user.is_anonymous == True %}
        <h1 class="text-center my-3">You are not authorized to access this page</h1>
        <p>Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
    {% else %}
        <p> No tasks have been created</p>
    {% endif %}

{% endblock %}

todolist/templates/todolist/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
	<div class="container">
	  <div class="row">
	    <div class="col-6 offset-3">
	      <h1 class="text-center my-3">Login</h1>
	      {% if error == True %}
	        <p class="text-danger">Invalid user credentials, please check your username and password</p>
	      {% endif %}
	      <form action="{% url 'todolist:login' %}" method="post">
	        <!-- This template tag provides protection against Cross Site Request Forgeries (CSRF) -->
	        <!-- CSRF occurs when a malicious website contains a link, a form button or some JavaScript that is intended to perform some action our website, using the credentials of a logged-in user -->
	        {% csrf_token %}

	        <div class="mb-3">
	            <label for="username">Username: </label>
	            <input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
	        </div>

	        <div class="mb-3">
	            <label for="password">Password: </label>
	            <input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
	        </div>

	        <div class="text-center">
	            <input class="btn btn-primary" type="submit" value="Login">
	        </div>

	      </form>
	    </div>
	  </div>
	</div>

{% endblock %}

todolist/templates/todolist/register.html
{% extends 'base.html' %}

{% block title %}Registration{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-white">
                    <h3 class="text-center text-primary">Register</h3>
                </div>
                <div class="card-body">
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        {{ message }}
                    </div>
                    {% endfor %}
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="{{ form.username.id_for_label }}">Username:</label>
                            <input type="text" name="username" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label for="{{ form.first_name.id_for_label }}">First Name:</label>
                            <input type="text" name="first_name" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label for="{{ form.last_name.id_for_label }}">Last Name:</label>
                            <input type="text" name="last_name" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label for="{{ form.email.id_for_label }}">Email:</label>
                            <input type="email" name="email" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label for="{{ form.password.id_for_label }}">Password:</label>
                            <input type="password" name="password" class="form-control" required>
                        </div>
                        <!-- Assuming you have a confirm_password field in your form -->
                        <div class="form-group">
                            <label for="{{ form.confirm_password.id_for_label }}">Confirm Password:</label>
                            <input type="password" name="confirm_password" class="form-control" required>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary mt-3">Register</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

todolist/templates/todolist/todoitem.html
{% extends 'base.html'%}

{% block title %} To Do Item {% endblock %}

{% block content %}
	<div class="text-center my-3">
		<h1>{{ task_name }}</h1>
		<h3>Description</h3>
		<p>{{ description }}</p>
		<h3>Status</h3>
		<p>{{ status }}</p>
		
		<button class="btn btn-primary mx-1 text-decoration-none">
			<a href="{% url 'todolist:update_task' id %}" class="text-light text-decoration-none">Edit Task</a>
		</button>

		<button class="btn btn-danger mx-1 text-decoration-none">
			<a href="{% url 'todolist:delete_task' id %}" class="text-light text-decoration-none">Delete Task</a>
		</button>

		<button class="btn btn-warning mx-1 text-decoration-none">
			<a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">Back To Tasks</a>
		</button>
		
	</div>

{% endblock %}

todolist/templates/todolist/update_task.html
{% extends 'base.html' %}

{% block title %}Update Task{% endblock %}

{% block content %}
  {% if user.is_anonymous == False %}
    <div class="container">
      <div class="row">
        <div class="col-6 offset-3">
          <h1 class="text-center my-3">Update Task</h1>
          {% if error == True %}
            <p class="text-danger">Task not found</p>
          {% endif %}
          <form action="{% url 'todolist:update_task' todoitem_id %}" method="post">
            {% csrf_token %}

            <div class="mb-3">
                <label for="task_name">Task Name: </label>
                <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
            </div>

            <div class="mb-3">
                <label for="description">Description: </label>
                <textarea class="form-control" name="description" required>{{ description }}</textarea>
            </div>

            <div class="mb-3">
                <label for="status">Status: </label>
                <input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
            </div>

            <div class="text-center">
                <input class="btn btn-success" type="submit" value="Update Task">
            </div>

          </form>
        </div>
      </div>
    </div>
  {% else %}
    <h1 class="text-center my-3">You are not authorized to access this page.</h1>
    <p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
  {% endif %}
{% endblock %}

todolist/templates/todolist/update_user.html
{% extends 'base.html' %}

{% block title %}Update User{% endblock %}

{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <div class="card-header bg-white">
            <h3 class="text-center text-success">Update User Information</h3>
          </div>
          <div class="card-body">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">
              {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            <form method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <div class="text-center">
                <button type="submit" class="btn btn-primary mt-3">Update User</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}